
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TokenBridgeContractArtifactJson from './TokenBridge.json' with { type: 'json' };
export const TokenBridgeContractArtifact = loadContractArtifact(TokenBridgeContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract TokenBridge;
 */
export class TokenBridgeContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, TokenBridgeContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, TokenBridgeContract.artifact, wallet) as Promise<TokenBridgeContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, wormhole_address: AztecAddressLike, chain_id: (bigint | number), owner: AztecAddressLike, message_fee: (bigint | number)) {
    return new DeployMethod<TokenBridgeContract>(PublicKeys.default(), wallet, TokenBridgeContractArtifact, TokenBridgeContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, wormhole_address: AztecAddressLike, chain_id: (bigint | number), owner: AztecAddressLike, message_fee: (bigint | number)) {
    return new DeployMethod<TokenBridgeContract>(publicKeys, wallet, TokenBridgeContractArtifact, TokenBridgeContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TokenBridgeContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TokenBridgeContract['methods'][M]>
  ) {
    return new DeployMethod<TokenBridgeContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TokenBridgeContractArtifact,
      TokenBridgeContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TokenBridgeContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TokenBridgeContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'owner' | 'token_configs' | 'remote_tokens' | 'registered_emitters' | 'processed_vaas' | 'message_fee' | 'last_received_value' | 'last_received_from_chain' | 'last_received_sender'> {
      return {
        config: {
      slot: new Fr(1n),
    },
owner: {
      slot: new Fr(5n),
    },
token_configs: {
      slot: new Fr(6n),
    },
remote_tokens: {
      slot: new Fr(7n),
    },
registered_emitters: {
      slot: new Fr(8n),
    },
processed_vaas: {
      slot: new Fr(9n),
    },
message_fee: {
      slot: new Fr(10n),
    },
last_received_value: {
      slot: new Fr(11n),
    },
last_received_from_chain: {
      slot: new Fr(12n),
    },
last_received_sender: {
      slot: new Fr(13n),
    }
      } as ContractStorageLayout<'config' | 'owner' | 'token_configs' | 'remote_tokens' | 'registered_emitters' | 'processed_vaas' | 'message_fee' | 'last_received_value' | 'last_received_from_chain' | 'last_received_sender'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** bridge_in_private(vaa_bytes: array, vaa_length: integer, destination_token: struct, recipient: struct, normalized_amount: integer, source_chain_id: integer, wormhole_address: struct) */
    bridge_in_private: ((vaa_bytes: (bigint | number)[], vaa_length: (bigint | number), destination_token: AztecAddressLike, recipient: AztecAddressLike, normalized_amount: (bigint | number), source_chain_id: (bigint | number), wormhole_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** bridge_out_private(token: struct, amount: integer, destination_chain_id: integer, recipient: array, fee_nonce: field, token_nonce: field, wormhole_address: struct, chain_id: integer, remote_token: array, is_native: boolean, decimals: integer, message_fee: integer) */
    bridge_out_private: ((token: AztecAddressLike, amount: (bigint | number), destination_chain_id: (bigint | number), recipient: (bigint | number)[], fee_nonce: FieldLike, token_nonce: FieldLike, wormhole_address: AztecAddressLike, chain_id: (bigint | number), remote_token: (bigint | number)[], is_native: boolean, decimals: (bigint | number), message_fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** bridge_out_public(token: struct, amount: integer, destination_chain_id: integer, recipient: array, fee_nonce: field, token_nonce: field) */
    bridge_out_public: ((token: AztecAddressLike, amount: (bigint | number), destination_chain_id: (bigint | number), recipient: (bigint | number)[], fee_nonce: FieldLike, token_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(wormhole_address: struct, chain_id: integer, owner: struct, message_fee: integer) */
    constructor: ((wormhole_address: AztecAddressLike, chain_id: (bigint | number), owner: AztecAddressLike, message_fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_last_test_message() */
    get_last_test_message: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_message_fee() */
    get_message_fee: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_owner() */
    get_owner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_registered_emitter(chain_id: integer) */
    get_registered_emitter: ((chain_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_remote_token(local_token: struct, remote_chain_id: integer) */
    get_remote_token: ((local_token: AztecAddressLike, remote_chain_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_token_config(token: struct) */
    get_token_config: ((token: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_vaa_processed(vaa_hash: field) */
    is_vaa_processed: ((vaa_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** receive_test_message(source_chain_id: integer, sender: field, value: field) */
    receive_test_message: ((source_chain_id: (bigint | number), sender: FieldLike, value: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_emitter(chain_id: integer, emitter_address: array) */
    register_emitter: ((chain_id: (bigint | number), emitter_address: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** send_test_message(destination_chain_id: integer, value: field, fee_nonce: field) */
    send_test_message: ((destination_chain_id: (bigint | number), value: FieldLike, fee_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_message_fee(fee: integer) */
    set_message_fee: ((fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_remote_token(local_token: struct, remote_chain_id: integer, remote_token: array, enabled: boolean) */
    set_remote_token: ((local_token: AztecAddressLike, remote_chain_id: (bigint | number), remote_token: (bigint | number)[], enabled: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_token_config(token: struct, enabled: boolean, is_native: boolean, decimals: integer) */
    set_token_config: ((token: AztecAddressLike, enabled: boolean, is_native: boolean, decimals: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_ownership(new_owner: struct) */
    transfer_ownership: ((new_owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
