
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import WormholeBridgeContractArtifactJson from './WormholeBridge.json' with { type: 'json' };
export const WormholeBridgeContractArtifact = loadContractArtifact(WormholeBridgeContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract WormholeBridge;
 */
export class WormholeBridgeContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, WormholeBridgeContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, WormholeBridgeContract.artifact, wallet) as Promise<WormholeBridgeContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, token_address: AztecAddressLike, wormhole_address: AztecAddressLike, chain_id: (bigint | number), fee: (bigint | number)) {
    return new DeployMethod<WormholeBridgeContract>(PublicKeys.default(), wallet, WormholeBridgeContractArtifact, WormholeBridgeContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, token_address: AztecAddressLike, wormhole_address: AztecAddressLike, chain_id: (bigint | number), fee: (bigint | number)) {
    return new DeployMethod<WormholeBridgeContract>(publicKeys, wallet, WormholeBridgeContractArtifact, WormholeBridgeContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof WormholeBridgeContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<WormholeBridgeContract['methods'][M]>
  ) {
    return new DeployMethod<WormholeBridgeContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      WormholeBridgeContractArtifact,
      WormholeBridgeContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return WormholeBridgeContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(WormholeBridgeContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'config' | 'fee'> {
      return {
        config: {
      slot: new Fr(1n),
    },
fee: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'config' | 'fee'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** bridge_out_private(recipient_address: array, amount: integer, bridge_nonce: field, fee_nonce: field) */
    bridge_out_private: ((recipient_address: (bigint | number)[], amount: (bigint | number), bridge_nonce: FieldLike, fee_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** bridge_out_private_flat(recipient_address: array, amount: integer, bridge_nonce: field, fee_nonce: field) */
    bridge_out_private_flat: ((recipient_address: (bigint | number)[], amount: (bigint | number), bridge_nonce: FieldLike, fee_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(token_address: struct, wormhole_address: struct, chain_id: integer, fee: integer) */
    constructor: ((token_address: AztecAddressLike, wormhole_address: AztecAddressLike, chain_id: (bigint | number), fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_config() */
    get_config: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_wormhole_message_fee() */
    get_wormhole_message_fee: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
